myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.user_login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('employees/',views.employees,name='employees'),
    path('employees/<str:name>',views.employee,name='employee')
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('',include('myapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from datetime import time
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
    
class Employee(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    contact = models.CharField(max_length=15,blank=True)
    image = models.ImageField(upload_to='products',blank=True,null=True)
    job_title = models.CharField(max_length=50,blank=True)
    years_of_working = models.PositiveIntegerField(default=0)
    gender = models.CharField(max_length=1,choices=[('M','Male'),('F','Female'),('O','Other')],blank=True)
    department = models.CharField(max_length=50,blank=True)
    hire_date = models.DateTimeField(auto_now_add=True)
    salary = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    designation = models.CharField(choices=[('E','Employee'),('H','HR Manager'),('A','Admin')],max_length=1)

    def __str__(self):
        return self.user.username

myapp/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout,authenticate,login
from django.db.models import Q
from django.contrib import messages
from .decorators import hr_or_admin_required
from .models import User,Employee

def home(request):
    if request.user.is_authenticated:
        employee = Employee.objects.filter(user = request.user).first()
        return render(request, 'home.html',{'employee': employee})
    else:
        return render(request, 'home.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            messages.error(request, "Invalid credentials !")
            return redirect('/login')
    return render(request,'login.html')

def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        designation = request.POST.get('designation')
        if password1 != password2:
            messages.info(request,"Passwords don't match !")
            return redirect('signup')
        elif User.objects.filter(email = email).exists():
            messages.info(request, "Email already taken !")
            return redirect('signup')
        elif User.objects.filter(username = username).exists():
            messages.info(request, "Username already taken !")
            return redirect('signup')
        else:
            user = User.objects.create_user(username = username,email = email, password = password1)
            user.save()
            Employee.objects.create(user = user,designation=designation)
            return redirect('login')
    else:
        return render(request, 'register.html') 

@login_required(login_url='/users/login')
def user_logout(request):
    logout(request)
    return redirect('/')   

@hr_or_admin_required
def employees(request):
    employee = Employee.objects.filter(user = request.user).first()
    if employee.designation == 'A':
        employees = Employee.objects.filter(Q(designation__in=['H', 'E']) | Q(user=request.user)).exclude(user = request.user)
    else:
        employees = Employee.objects.filter(designation='E')
    return render(request,'employees.html',{ 'employees' : employees,'employee':employee })

def employee(request,name):
    print(name)
    employee = Employee.objects.filter(user__username = name).first()
    return render(request,'employee.html',{ 'employee': employee })

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="csrf-token" content="{{ csrf_token }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% include "css.html" %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body class="overflow-x-hidden">
    {% block main %} {% endblock main %} 
    {% if debug %}
    <script src="http://127.0.0.1:8000/__reload__/reload.js"></script>
    {% endif %}
  </body>
</html>

templates/css.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/output.css' %}" />

templates/employee.html
{% extends "index.html" %}
{% load static %}
{% block title %}Employee Profile{% endblock title %}
{% block content %}
<div class="flex flex-col min-h-[100dvh] bg-slate-300">
    <div style="background: url({% static "images/profile_banner.png" %}) no-repeat center;background-size:cover;" class="relative h-[35dvh] before:content-[''] before:bg-[rgba(0,0,0,.4)] before:absolute before:inset-0"></div>
    <div class="relative flex min-h-[65dvh] justify-evenly items-start">
    <div class="absolute flex flex-col gap-[1rem] -top-[7rem] left-[5rem]">
        <img src={% if employee.image %}"{{employee.image.url}}"{% else %}{% if employee.get_gender_display == "Male" %}"{% static "images/avatar_male.png" %}"{% else %}"{% static "images/avatar_female.png" %}"{% endif %}{% endif %} alt="{{employee.user.username}}" class="size-[15rem] rounded-[100rem]">
        <div class="text-lg opacity-60 font-semibold">EMPLOYEE DETAILS</div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Name</div>
            <div class="text-lg capitalize font-semibold">{{ employee.user.username }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Gender</div>
            <div class="text-lg capitalize font-semibold">{{ employee.get_gender_display }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Contact</div>
            <div class="text-lg capitalize font-semibold">{{ employee.contact }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Position</div>
            <div class="text-lg capitalize font-semibold">{{ employee.job_title }}</div>
        </div>
    </div>
    <div class="w-[16rem] flex flex-col gap-[1rem] mt-[5rem]">
        <div class="text-lg opacity-60 font-semibold">ROLE</div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Role</div>
            <div class="text-lg capitalize font-semibold">{{ employee.get_designation_display }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Department</div>
            <div class="text-lg capitalize font-semibold">{{ employee.department }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Experience</div>
            <div class="text-lg capitalize font-semibold">{{ employee.years_of_working }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Date Joined</div>
            <div class="text-lg capitalize font-semibold">{{ employee.hire_date|date:"F j, Y" }}</div>
        </div>
    </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
      updatePerformanceChart({{ employee.user.id }});
      updateAttendanceChart({{ employee.user.id }});
    });
  </script>
{% endblock content %}

templates/employees.html
{% extends "index.html" %}
{% load static %}
{% block title %}Employees{% endblock title %}
{% block content %}
<div class="min-h-[70dvh] grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-[3rem] p-[3rem]">
    {% for item in employees %}
    <div 
        onclick="window.location.href ='/employees/{{ item.user.username }}'"
        class="flex flex-col gap-2 items-center p-[1rem] h-[20rem] border-2 border-black transition-all hover:scale-[1.01] hover:shadow-2xl overflow-hidden">
        <div class="w-[25ch] text-ellipsis text-center whitespace-nowrap text-2xl font-semibold capitalize overflow-hidden">{{ item.user.username }}</div>
        <img src={% if item.get_gender_display == "Male" %}
        "{% static "images/avatar_male.png" %}"
        {% else %}
        "{% static "images/avatar_female.png" %}"
        {% endif %} alt="{{ item.name }}" class="w-1/2 h-1/2">
        <div class="py-[.5rem] w-[5rem] rounded-xl capitalize text-ellipsis text-center text-white whitespace-nowrap overflow-hidden {% if item.get_gender_display == 'Male' %}bg-blue-600{% else %}bg-pink-600{% endif %}">{{ item.get_gender_display }}</div>
        <div class="w-[25ch] text-ellipsis text-center whitespace-nowrap overflow-hidden">Role: {{ item.job_title }}</div>
        <div class="w-[29ch] text-ellipsis text-center whitespace-nowrap overflow-hidden">Department: {{ item.department }}</div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/footer.html
<div class="flex flex-col bg-white justify-center items-center pb-[2rem]">
  <div class="flex items-center justify-center text-md my-[2rem] gap-6">
      <a href="/" class="">Home</a>
      {% if employee.designation != "E" %}
      <a href="/employees" class="">Employees</a>
      {% endif %}
      <a href="/features" class="">Features</a>
      <a href="/contact" class="">Contact</a>
      <a href="/about" class="">About</a>
    </div>
    <div class="text-center">&copy;2024 Company.Inc</div>
</div>

templates/home.html
{% extends "index.html" %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
<div class="flex flex-col min-h-[100dvh]">
    <div class="flex items-center justify-around bg-sky-600 p-[2rem_4rem]">
        <div class="flex flex-col gap-3">
            <div class="text-6xl font-semibold w-[20ch]">Welcome to HR Management System</div>
            <div class="text-2xl font-light">We are here to Help you Manage <span class="underline underline-offset-2 [text-decoration-thickness:.2rem] font-bold">Human Resources</span></div>
        </div>
        <div class="flex justify-center items-center rounded-[50rem] bg-sky-100 h-[25rem] aspect-square">
            <img class="h-[20rem]" src="{% static "images/hero_image.webp" %}" alt="Hero Banner">
        </div>
    </div>
    <div class="bg-sky-600 h-[5rem] rounded-b-[50%]"></div>
</div>
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block main %}
<div class="min-h-[100dvh] flex flex-col">
  <div class="flex items-center justify-between px-[5vw] h-[10dvh] bg-white">
    <div class="font-bold text-3xl text-sky-400">HR Management System</div>
    <div class="flex items-center justify-center text-lg gap-6">
      <a href="/" class="">Home</a>
      {% if employee.designation != "E" %}
      <a href="/employees" class="">Employees</a>
      {% endif %}
      <a href="/features" class="">Features</a>
      <a href="/contact" class="">Contact</a>
      <a href="/about" class="">About</a>
    </div>
    <div class="flex items-center text-lg font-medium gap-[2rem]">
      {% if user.username %}
      <div onclick="window.location.href='/employees/{{request.user.id}}'" class="cursor-pointer">Hello {{ user.username }} !</div>
      <a
        href="/logout"
        class="h-[6dvh] w-[7vw] flex justify-center items-center rounded-xl border-4 border-sky-400 transition-colors hover:text-white hover:bg-sky-400"
      >
        Logout
      </a>
      {% else %}
      <a
        href="/login"
        class="h-[6dvh] w-[7vw] flex justify-center items-center rounded-xl border-4 border-sky-400 transition-colors hover:text-white hover:bg-sky-400"
      >
        Login
      </a>
      <a
        href="/signup"
        class="h-[6dvh] w-[7vw] flex justify-center items-center rounded-xl border-4 border-sky-400 text-white bg-sky-400 hover:bg-white hover:text-black"
      >
        Sign up
      </a>
      {% endif %}
    </div>
  </div>
  <hr class="h-[.1rem] bg-black" />
  {% block content %}{% endblock content %}
  <hr class="h-[.1rem] bg-black" />
  {% include "footer.html" %}
</div>
{% endblock main %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HR Management System</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        body {
            min-height:100dvh;
            background-color: #f8f9fa;
            color: #333;
            display:flex;
            flex-direction:column;
            justify-content:space-between;
        }

        .navbar {
            background-color: #ffffff;
        }

        .navbar-light .navbar-nav .nav-link {
            color: #000;
        }

        .navbar-light .navbar-nav .nav-link:hover {
            color: #007bff;
        }

        footer {
            background-color: #f1f1f1;
            color: #333;
        }

        form {
          position:absolute;
          top:25%;
          left:35%;
          background-color: #ffffff;
          padding: 20px 30px;
          border-radius: 8px;
          box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
          width: 100%;
          max-width: 400px;
        }
      
        form div {
          margin-bottom: 15px;
        }
      
        form label {
          display: block;
          margin-bottom: 5px;
          font-weight: bold;
          color: #333;
        }
      
        form input[type="text"],
        form input[type="password"] {
          width: 100%;
          padding: 10px;
          border: 1px solid #ccc;
          border-radius: 4px;
          font-size: 14px;
          box-sizing: border-box;
        }
      
        form input[type="text"]:focus,
        form input[type="password"]:focus {
          outline: none;
          border-color: #4CAF50;
          box-shadow: 0 0 5px rgba(72, 181, 68, 0.5);
        }
      
        form button {
          width: 100%;
          padding: 10px;
          background-color: #4CAF50;
          border: none;
          color: white;
          font-size: 16px;
          border-radius: 4px;
          cursor: pointer;
          transition: background-color 0.3s;
        }
      
        form button:hover {
          background-color: #45a049;
        }
      
        form div {
          display: inline-block;
          margin-left: 10px;
          cursor: pointer;
          vertical-align: middle;
        }
      
        form div svg {
          fill: #5f6368;
          transition: fill 0.3s ease-in-out;
        }
      
        form div:hover svg {
          fill: #4CAF50;
        }
      
        form div svg:active {
          transform: scale(0.9);
        }

    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
        <a class="navbar-brand" href="/">HR Management System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>

    </div>
</nav>
<form method="post" style="display:flex;flex-direction:column;align-items:center;gap:1rem;padding:3rem 0;">
  {% for message in messages %}
  <div style="color:red;">{{message}}</div>
  {% endfor %}
  {% csrf_token %}
    <div style="width:80%">
      <label for="username">Username:</label>
      <input
        name="username"
        id="username"
        type="text"
        value="{{ form.username.value | default:'' }}"
      />
    </div>
    <div style="position:relative;width:80%;">
      <label for="password">Password:</label>
      <input
        name="password"
        id="password"
        type="password"
      />
      <div style="position:absolute;top:1.9rem;right:.4rem;" onclick="togglePassword('password')">
        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#5f6368"><path d="m644-428-58-58q9-47-27-88t-93-32l-58-58q17-8 34.5-12t37.5-4q75 0 127.5 52.5T660-500q0 20-4 37.5T644-428Zm128 126-58-56q38-29 67.5-63.5T832-500q-50-101-143.5-160.5T480-720q-29 0-57 4t-55 12l-62-62q41-17 84-25.5t90-8.5q151 0 269 83.5T920-500q-23 59-60.5 109.5T772-302Zm20 246L624-222q-35 11-70.5 16.5T480-200q-151 0-269-83.5T40-500q21-53 53-98.5t73-81.5L56-792l56-56 736 736-56 56ZM222-624q-29 26-53 57t-41 67q50 101 143.5 160.5T480-280q20 0 39-2.5t39-5.5l-36-38q-11 3-21 4.5t-21 1.5q-75 0-127.5-52.5T300-500q0-11 1.5-21t4.5-21l-84-82Zm319 93Zm-151 75Z"/></svg>
      </div>
    </div>
    <button type="submit" style="width:6rem;">Login</button>
    <div style="padding-top:1rem;">Don't have an account?<a href="/signup">Register</a></div>
  </form>
  
  <script>
    function togglePassword(fieldId) {
      const field = document.getElementById(fieldId);
      const toggleIcon = field.nextElementSibling.querySelector('svg');
    
      // Toggle password visibility
      if (field.type === "password") {
        field.type = "text";
        toggleIcon.innerHTML = `
         <path d="M480-320q75 0 127.5-52.5T660-500q0-75-52.5-127.5T480-680q-75 0-127.5 52.5T300-500q0 75 52.5 127.5T480-320Zm0-72q-45 0-76.5-31.5T372-500q0-45 31.5-76.5T480-608q45 0 76.5 31.5T588-500q0 45-31.5 76.5T480-392Zm0 192q-146 0-266-81.5T40-500q54-137 174-218.5T480-800q146 0 266 81.5T920-500q-54 137-174 218.5T480-200Zm0-300Zm0 220q113 0 207.5-59.5T832-500q-50-101-144.5-160.5T480-720q-113 0-207.5 59.5T128-500q50 101 144.5 160.5T480-280Z"/>
        `;
      } else {
        field.type = "password";
        toggleIcon.innerHTML = `
          <path d="m644-428-58-58q9-47-27-88t-93-32l-58-58q17-8 34.5-12t37.5-4q75 0 127.5 52.5T660-500q0 20-4 37.5T644-428Zm128 126-58-56q38-29 67.5-63.5T832-500q-50-101-143.5-160.5T480-720q-29 0-57 4t-55 12l-62-62q41-17 84-25.5t90-8.5q151 0 269 83.5T920-500q-23 59-60.5 109.5T772-302Zm20 246L624-222q-35 11-70.5 16.5T480-200q-151 0-269-83.5T40-500q21-53 53-98.5t73-81.5L56-792l56-56 736 736-56 56ZM222-624q-29 26-53 57t-41 67q50 101 143.5 160.5T480-280q20 0 39-2.5t39-5.5l-36-38q-11 3-21 4.5t-21 1.5q-75 0-127.5-52.5T300-500q0-11 1.5-21t4.5-21l-84-82Zm319 93Zm-151 75Z"/>
        `;
      }
    }
    </script>
    </body>
    </html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HR Management System</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    {% include "css.html" %}
    <style>
        body {
            min-height:100dvh;
            background-color: #f8f9fa;
            color: #333;
            display:flex;
            flex-direction:column;
            justify-content:space-between;
        }

        .navbar {
            background-color: #ffffff;
        }

        .navbar-light .navbar-nav .nav-link {
            color: #000;
        }

        .navbar-light .navbar-nav .nav-link:hover {
            color: #007bff;
        }

        footer {
            background-color: #f1f1f1;
            color: #333;
        }
      
        form {
          position:absolute;
          left:35%;
          top:17%;
          background-color: #ffffff;
          padding: 20px 30px;
          border-radius: 8px;
          box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
          width: 100%;
          max-width: 400px;
        }
      
        form div {
          margin-bottom: 15px;
        }
      
        form label {
          display: block;
          margin-bottom: 5px;
          font-weight: bold;
          color: #333;
        }
      
        form input[type="text"],
        form input[type="email"],
        form input[type="password"] {
          width: 100%;
          padding: 10px;
          border: 1px solid black;
          border-radius: 4px;
          font-size: 14px;
          box-sizing: border-box;
        }
      
        form input[type="text"]:focus,
        form input[type="email"]:focus,
        form input[type="password"]:focus {
          outline: none;
          border-color: #4CAF50;
          box-shadow: 0 0 5px rgba(72, 181, 68, 0.5);
        }
      
        form button {
          width: 100%;
          padding: 10px;
          background-color: #4CAF50;
          border: none;
          color: white;
          font-size: 16px;
          border-radius: 4px;
          cursor: pointer;
          transition: background-color 0.3s;
        }
      
        form button:hover {
          background-color: #45a049;
        }
      
        form div {
          display: inline-block;
          margin-left: 10px;
          cursor: pointer;
          vertical-align: middle;
        }
      
        form div svg {
          fill: #5f6368;
          transition: fill 0.3s ease-in-out;
        }
      
        form div:hover svg {
          fill: #4CAF50;
        }
      
        form div svg:active {
          transform: scale(0.9);
        }
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
        <a class="navbar-brand" href="/">HR Management System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            </ul>
        </div>
    </div>
</nav>
<form method="post" style="display:flex;flex-direction:column;align-items:center;gap:1rem;padding:3rem 0;">
    {% for message in messages %}
    <div>{{message}}</div>
    {% endfor %}

      {% csrf_token %}
      <div style="width:80%">
        <label for="username">Username:</label>
        <input
          name="username"
          id="username"
          type="text"
          value="{{ form.username.value | default:'' }}"
        />
      </div>
      <div style="width:80%">
        <label for="email">Email:</label>
        <input
          name="email"
          id="email"
          type="email"
          value="{{ form.email.value | default:'' }}"
        />
      </div>
      <div style="position:relative;width:80%;">
        <label for="password1">Password:</label>
        <input
          name="password1"
          id="password1"
          type="password"
        />
        <div style="position:absolute;top:1.9rem;right:.4rem;" onclick="togglePassword('password1')">
          <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#5f6368"><path d="m644-428-58-58q9-47-27-88t-93-32l-58-58q17-8 34.5-12t37.5-4q75 0 127.5 52.5T660-500q0 20-4 37.5T644-428Zm128 126-58-56q38-29 67.5-63.5T832-500q-50-101-143.5-160.5T480-720q-29 0-57 4t-55 12l-62-62q41-17 84-25.5t90-8.5q151 0 269 83.5T920-500q-23 59-60.5 109.5T772-302Zm20 246L624-222q-35 11-70.5 16.5T480-200q-151 0-269-83.5T40-500q21-53 53-98.5t73-81.5L56-792l56-56 736 736-56 56ZM222-624q-29 26-53 57t-41 67q50 101 143.5 160.5T480-280q20 0 39-2.5t39-5.5l-36-38q-11 3-21 4.5t-21 1.5q-75 0-127.5-52.5T300-500q0-11 1.5-21t4.5-21l-84-82Zm319 93Zm-151 75Z"/></svg>
        </div>
      </div>
      <div style="position:relative;width:80%;">
        <label for="password2">Confirm Password:</label>
        <input
        name="password2"
        id="password2"
        type="password"
      />
        <div style="position:absolute;top:1.9rem;right:.4rem;" onclick="togglePassword('password2')">
          <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#5f6368"><path d="m644-428-58-58q9-47-27-88t-93-32l-58-58q17-8 34.5-12t37.5-4q75 0 127.5 52.5T660-500q0 20-4 37.5T644-428Zm128 126-58-56q38-29 67.5-63.5T832-500q-50-101-143.5-160.5T480-720q-29 0-57 4t-55 12l-62-62q41-17 84-25.5t90-8.5q151 0 269 83.5T920-500q-23 59-60.5 109.5T772-302Zm20 246L624-222q-35 11-70.5 16.5T480-200q-151 0-269-83.5T40-500q21-53 53-98.5t73-81.5L56-792l56-56 736 736-56 56ZM222-624q-29 26-53 57t-41 67q50 101 143.5 160.5T480-280q20 0 39-2.5t39-5.5l-36-38q-11 3-21 4.5t-21 1.5q-75 0-127.5-52.5T300-500q0-11 1.5-21t4.5-21l-84-82Zm319 93Zm-151 75Z"/></svg>
        </div>
      </div>
      <div class="border border-black rounded-lg p-[.6rem_3.5rem]">Designation:
        <select class="outline-none" name="designation">
        <option class="" value="E">Employee</option>
        <option class="" value="H">HR Manager</option>
        <option class="" value="A">Admin</option>
      </select>
    </div>
      <button type="submit" style="width:6rem;">Register</button>
    </form>
    
    <script>
      function togglePassword(fieldId) {
        const field = document.getElementById(fieldId);
        const toggleIcon = field.nextElementSibling.querySelector('svg');
      
        // Toggle password visibility
        if (field.type === "password") {
          field.type = "text";
          toggleIcon.innerHTML = `
           <path d="M480-320q75 0 127.5-52.5T660-500q0-75-52.5-127.5T480-680q-75 0-127.5 52.5T300-500q0 75 52.5 127.5T480-320Zm0-72q-45 0-76.5-31.5T372-500q0-45 31.5-76.5T480-608q45 0 76.5 31.5T588-500q0 45-31.5 76.5T480-392Zm0 192q-146 0-266-81.5T40-500q54-137 174-218.5T480-800q146 0 266 81.5T920-500q-54 137-174 218.5T480-200Zm0-300Zm0 220q113 0 207.5-59.5T832-500q-50-101-144.5-160.5T480-720q-113 0-207.5 59.5T128-500q50 101 144.5 160.5T480-280Z"/>
          `;
        } else {
          field.type = "password";
          toggleIcon.innerHTML = `
            <path d="m644-428-58-58q9-47-27-88t-93-32l-58-58q17-8 34.5-12t37.5-4q75 0 127.5 52.5T660-500q0 20-4 37.5T644-428Zm128 126-58-56q38-29 67.5-63.5T832-500q-50-101-143.5-160.5T480-720q-29 0-57 4t-55 12l-62-62q41-17 84-25.5t90-8.5q151 0 269 83.5T920-500q-23 59-60.5 109.5T772-302Zm20 246L624-222q-35 11-70.5 16.5T480-200q-151 0-269-83.5T40-500q21-53 53-98.5t73-81.5L56-792l56-56 736 736-56 56ZM222-624q-29 26-53 57t-41 67q50 101 143.5 160.5T480-280q20 0 39-2.5t39-5.5l-36-38q-11 3-21 4.5t-21 1.5q-75 0-127.5-52.5T300-500q0-11 1.5-21t4.5-21l-84-82Zm319 93Zm-151 75Z"/>
          `;
        }
      }
      </script>
      </body>
      </html>